SET GLOBAL event_scheduler=ON;

CREATE TABLE IF NOT EXISTS rules (
   id int(10) unsigned NOT NULL AUTO_INCREMENT,
   body json DEFAULT NULL,
   `active` tinyint(1) DEFAULT 0,
   PRIMARY KEY (id)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
  
CREATE EVENT AutoDeleteOldRestLog
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
DELETE LOW_PRIORITY FROM rest_logger WHERE date < DATE_SUB(NOW(), INTERVAL 14 DAY);

CREATE EVENT AutoDeleteOldLog
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
DELETE LOW_PRIORITY FROM logger WHERE date < DATE_SUB(NOW(), INTERVAL 14 DAY);

CREATE EVENT AutoDeleteOldRules
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
delete LOW_PRIORITY FROM rules WHERE id < (select id from (select max(id)-10 as id from rules) t);